//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Babble", "PollEventPollResponse", "PollEvent", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Bti.Babble.Model.Entity.PollEvent), "PollResponse", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Bti.Babble.Model.Entity.PollResponse), true)]

#endregion

namespace Bti.Babble.Model.Entity
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BabbleContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BabbleContainer object using the connection string found in the 'BabbleContainer' section of the application configuration file.
        /// </summary>
        public BabbleContainer() : base("name=BabbleContainer", "BabbleContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BabbleContainer object.
        /// </summary>
        public BabbleContainer(string connectionString) : base(connectionString, "BabbleContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BabbleContainer object.
        /// </summary>
        public BabbleContainer(EntityConnection connection) : base(connection, "BabbleContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BabbleEvent> BabbleEvents
        {
            get
            {
                if ((_BabbleEvents == null))
                {
                    _BabbleEvents = base.CreateObjectSet<BabbleEvent>("BabbleEvents");
                }
                return _BabbleEvents;
            }
        }
        private ObjectSet<BabbleEvent> _BabbleEvents;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PollResponse> PollResponses
        {
            get
            {
                if ((_PollResponses == null))
                {
                    _PollResponses = base.CreateObjectSet<PollResponse>("PollResponses");
                }
                return _PollResponses;
            }
        }
        private ObjectSet<PollResponse> _PollResponses;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BabbleEvents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBabbleEvents(BabbleEvent babbleEvent)
        {
            base.AddObject("BabbleEvents", babbleEvent);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PollResponses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPollResponses(PollResponse pollResponse)
        {
            base.AddObject("PollResponses", pollResponse);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Babble", Name="BabbleEvent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(PollEvent))]
    [KnownTypeAttribute(typeof(CommentEvent))]
    [KnownTypeAttribute(typeof(CouponEvent))]
    [KnownTypeAttribute(typeof(StoryEvent))]
    [KnownTypeAttribute(typeof(InfoEvent))]
    public partial class BabbleEvent : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BabbleEvent object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="pubDate">Initial value of the PubDate property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="user">Initial value of the User property.</param>
        /// <param name="message">Initial value of the Message property.</param>
        /// <param name="image">Initial value of the Image property.</param>
        /// <param name="time">Initial value of the Time property.</param>
        /// <param name="large">Initial value of the Large property.</param>
        public static BabbleEvent CreateBabbleEvent(global::System.Int32 id, global::System.DateTime pubDate, global::System.String type, global::System.String user, global::System.String message, global::System.String image, global::System.String time, global::System.String large)
        {
            BabbleEvent babbleEvent = new BabbleEvent();
            babbleEvent.Id = id;
            babbleEvent.PubDate = pubDate;
            babbleEvent.Type = type;
            babbleEvent.User = user;
            babbleEvent.Message = message;
            babbleEvent.Image = image;
            babbleEvent.Time = time;
            babbleEvent.Large = large;
            return babbleEvent;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime PubDate
        {
            get
            {
                return _PubDate;
            }
            set
            {
                OnPubDateChanging(value);
                ReportPropertyChanging("PubDate");
                _PubDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PubDate");
                OnPubDateChanged();
            }
        }
        private global::System.DateTime _PubDate;
        partial void OnPubDateChanging(global::System.DateTime value);
        partial void OnPubDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String User
        {
            get
            {
                return _User;
            }
            set
            {
                OnUserChanging(value);
                ReportPropertyChanging("User");
                _User = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("User");
                OnUserChanged();
            }
        }
        private global::System.String _User;
        partial void OnUserChanging(global::System.String value);
        partial void OnUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Image
        {
            get
            {
                return _Image;
            }
            set
            {
                OnImageChanging(value);
                ReportPropertyChanging("Image");
                _Image = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Image");
                OnImageChanged();
            }
        }
        private global::System.String _Image;
        partial void OnImageChanging(global::System.String value);
        partial void OnImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Time
        {
            get
            {
                return _Time;
            }
            set
            {
                OnTimeChanging(value);
                ReportPropertyChanging("Time");
                _Time = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Time");
                OnTimeChanged();
            }
        }
        private global::System.String _Time;
        partial void OnTimeChanging(global::System.String value);
        partial void OnTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Large
        {
            get
            {
                return _Large;
            }
            set
            {
                OnLargeChanging(value);
                ReportPropertyChanging("Large");
                _Large = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Large");
                OnLargeChanged();
            }
        }
        private global::System.String _Large;
        partial void OnLargeChanging(global::System.String value);
        partial void OnLargeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Babble", Name="CommentEvent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CommentEvent : BabbleEvent
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CommentEvent object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="pubDate">Initial value of the PubDate property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="user">Initial value of the User property.</param>
        /// <param name="message">Initial value of the Message property.</param>
        /// <param name="image">Initial value of the Image property.</param>
        /// <param name="time">Initial value of the Time property.</param>
        /// <param name="large">Initial value of the Large property.</param>
        public static CommentEvent CreateCommentEvent(global::System.Int32 id, global::System.DateTime pubDate, global::System.String type, global::System.String user, global::System.String message, global::System.String image, global::System.String time, global::System.String large)
        {
            CommentEvent commentEvent = new CommentEvent();
            commentEvent.Id = id;
            commentEvent.PubDate = pubDate;
            commentEvent.Type = type;
            commentEvent.User = user;
            commentEvent.Message = message;
            commentEvent.Image = image;
            commentEvent.Time = time;
            commentEvent.Large = large;
            return commentEvent;
        }

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Babble", Name="CouponEvent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CouponEvent : BabbleEvent
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CouponEvent object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="pubDate">Initial value of the PubDate property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="user">Initial value of the User property.</param>
        /// <param name="message">Initial value of the Message property.</param>
        /// <param name="image">Initial value of the Image property.</param>
        /// <param name="time">Initial value of the Time property.</param>
        /// <param name="large">Initial value of the Large property.</param>
        /// <param name="store">Initial value of the Store property.</param>
        /// <param name="coupon">Initial value of the Coupon property.</param>
        /// <param name="code">Initial value of the Code property.</param>
        /// <param name="link">Initial value of the Link property.</param>
        public static CouponEvent CreateCouponEvent(global::System.Int32 id, global::System.DateTime pubDate, global::System.String type, global::System.String user, global::System.String message, global::System.String image, global::System.String time, global::System.String large, global::System.String store, global::System.String coupon, global::System.String code, global::System.String link)
        {
            CouponEvent couponEvent = new CouponEvent();
            couponEvent.Id = id;
            couponEvent.PubDate = pubDate;
            couponEvent.Type = type;
            couponEvent.User = user;
            couponEvent.Message = message;
            couponEvent.Image = image;
            couponEvent.Time = time;
            couponEvent.Large = large;
            couponEvent.Store = store;
            couponEvent.Coupon = coupon;
            couponEvent.Code = code;
            couponEvent.Link = link;
            return couponEvent;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Store
        {
            get
            {
                return _Store;
            }
            set
            {
                OnStoreChanging(value);
                ReportPropertyChanging("Store");
                _Store = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Store");
                OnStoreChanged();
            }
        }
        private global::System.String _Store;
        partial void OnStoreChanging(global::System.String value);
        partial void OnStoreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Coupon
        {
            get
            {
                return _Coupon;
            }
            set
            {
                OnCouponChanging(value);
                ReportPropertyChanging("Coupon");
                _Coupon = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Coupon");
                OnCouponChanged();
            }
        }
        private global::System.String _Coupon;
        partial void OnCouponChanging(global::System.String value);
        partial void OnCouponChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                OnCodeChanging(value);
                ReportPropertyChanging("Code");
                _Code = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Code");
                OnCodeChanged();
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Link
        {
            get
            {
                return _Link;
            }
            set
            {
                OnLinkChanging(value);
                ReportPropertyChanging("Link");
                _Link = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Link");
                OnLinkChanged();
            }
        }
        private global::System.String _Link;
        partial void OnLinkChanging(global::System.String value);
        partial void OnLinkChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Babble", Name="InfoEvent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class InfoEvent : BabbleEvent
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new InfoEvent object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="pubDate">Initial value of the PubDate property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="user">Initial value of the User property.</param>
        /// <param name="message">Initial value of the Message property.</param>
        /// <param name="image">Initial value of the Image property.</param>
        /// <param name="time">Initial value of the Time property.</param>
        /// <param name="large">Initial value of the Large property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="link">Initial value of the Link property.</param>
        /// <param name="infoImage">Initial value of the InfoImage property.</param>
        public static InfoEvent CreateInfoEvent(global::System.Int32 id, global::System.DateTime pubDate, global::System.String type, global::System.String user, global::System.String message, global::System.String image, global::System.String time, global::System.String large, global::System.String title, global::System.String description, global::System.String link, global::System.String infoImage)
        {
            InfoEvent infoEvent = new InfoEvent();
            infoEvent.Id = id;
            infoEvent.PubDate = pubDate;
            infoEvent.Type = type;
            infoEvent.User = user;
            infoEvent.Message = message;
            infoEvent.Image = image;
            infoEvent.Time = time;
            infoEvent.Large = large;
            infoEvent.Title = title;
            infoEvent.Description = description;
            infoEvent.Link = link;
            infoEvent.InfoImage = infoImage;
            return infoEvent;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Link
        {
            get
            {
                return _Link;
            }
            set
            {
                OnLinkChanging(value);
                ReportPropertyChanging("Link");
                _Link = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Link");
                OnLinkChanged();
            }
        }
        private global::System.String _Link;
        partial void OnLinkChanging(global::System.String value);
        partial void OnLinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String InfoImage
        {
            get
            {
                return _InfoImage;
            }
            set
            {
                OnInfoImageChanging(value);
                ReportPropertyChanging("InfoImage");
                _InfoImage = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("InfoImage");
                OnInfoImageChanged();
            }
        }
        private global::System.String _InfoImage;
        partial void OnInfoImageChanging(global::System.String value);
        partial void OnInfoImageChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Babble", Name="PollEvent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PollEvent : BabbleEvent
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PollEvent object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="pubDate">Initial value of the PubDate property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="user">Initial value of the User property.</param>
        /// <param name="message">Initial value of the Message property.</param>
        /// <param name="image">Initial value of the Image property.</param>
        /// <param name="time">Initial value of the Time property.</param>
        /// <param name="large">Initial value of the Large property.</param>
        /// <param name="question">Initial value of the Question property.</param>
        /// <param name="votes">Initial value of the Votes property.</param>
        /// <param name="pollImage">Initial value of the PollImage property.</param>
        public static PollEvent CreatePollEvent(global::System.Int32 id, global::System.DateTime pubDate, global::System.String type, global::System.String user, global::System.String message, global::System.String image, global::System.String time, global::System.String large, global::System.String question, global::System.Int32 votes, global::System.String pollImage)
        {
            PollEvent pollEvent = new PollEvent();
            pollEvent.Id = id;
            pollEvent.PubDate = pubDate;
            pollEvent.Type = type;
            pollEvent.User = user;
            pollEvent.Message = message;
            pollEvent.Image = image;
            pollEvent.Time = time;
            pollEvent.Large = large;
            pollEvent.Question = question;
            pollEvent.Votes = votes;
            pollEvent.PollImage = pollImage;
            return pollEvent;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Question
        {
            get
            {
                return _Question;
            }
            set
            {
                OnQuestionChanging(value);
                ReportPropertyChanging("Question");
                _Question = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Question");
                OnQuestionChanged();
            }
        }
        private global::System.String _Question;
        partial void OnQuestionChanging(global::System.String value);
        partial void OnQuestionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Votes
        {
            get
            {
                return _Votes;
            }
            set
            {
                OnVotesChanging(value);
                ReportPropertyChanging("Votes");
                _Votes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Votes");
                OnVotesChanged();
            }
        }
        private global::System.Int32 _Votes;
        partial void OnVotesChanging(global::System.Int32 value);
        partial void OnVotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PollImage
        {
            get
            {
                return _PollImage;
            }
            set
            {
                OnPollImageChanging(value);
                ReportPropertyChanging("PollImage");
                _PollImage = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PollImage");
                OnPollImageChanged();
            }
        }
        private global::System.String _PollImage;
        partial void OnPollImageChanging(global::System.String value);
        partial void OnPollImageChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Babble", "PollEventPollResponse", "PollResponse")]
        public EntityCollection<PollResponse> PollResponses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PollResponse>("Babble.PollEventPollResponse", "PollResponse");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PollResponse>("Babble.PollEventPollResponse", "PollResponse", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Babble", Name="PollResponse")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PollResponse : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PollResponse object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="text">Initial value of the Text property.</param>
        /// <param name="votes">Initial value of the Votes property.</param>
        /// <param name="pollEventId">Initial value of the PollEventId property.</param>
        public static PollResponse CreatePollResponse(global::System.Int32 id, global::System.String text, global::System.Int32 votes, global::System.Int32 pollEventId)
        {
            PollResponse pollResponse = new PollResponse();
            pollResponse.Id = id;
            pollResponse.Text = text;
            pollResponse.Votes = votes;
            pollResponse.PollEventId = pollEventId;
            return pollResponse;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Votes
        {
            get
            {
                return _Votes;
            }
            set
            {
                OnVotesChanging(value);
                ReportPropertyChanging("Votes");
                _Votes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Votes");
                OnVotesChanged();
            }
        }
        private global::System.Int32 _Votes;
        partial void OnVotesChanging(global::System.Int32 value);
        partial void OnVotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PollEventId
        {
            get
            {
                return _PollEventId;
            }
            set
            {
                OnPollEventIdChanging(value);
                ReportPropertyChanging("PollEventId");
                _PollEventId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PollEventId");
                OnPollEventIdChanged();
            }
        }
        private global::System.Int32 _PollEventId;
        partial void OnPollEventIdChanging(global::System.Int32 value);
        partial void OnPollEventIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Babble", "PollEventPollResponse", "PollEvent")]
        public PollEvent PollEvent
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PollEvent>("Babble.PollEventPollResponse", "PollEvent").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PollEvent>("Babble.PollEventPollResponse", "PollEvent").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PollEvent> PollEventReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PollEvent>("Babble.PollEventPollResponse", "PollEvent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PollEvent>("Babble.PollEventPollResponse", "PollEvent", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Babble", Name="StoryEvent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StoryEvent : BabbleEvent
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new StoryEvent object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="pubDate">Initial value of the PubDate property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="user">Initial value of the User property.</param>
        /// <param name="message">Initial value of the Message property.</param>
        /// <param name="image">Initial value of the Image property.</param>
        /// <param name="time">Initial value of the Time property.</param>
        /// <param name="large">Initial value of the Large property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="link">Initial value of the Link property.</param>
        /// <param name="storyImage">Initial value of the StoryImage property.</param>
        /// <param name="storyText">Initial value of the StoryText property.</param>
        public static StoryEvent CreateStoryEvent(global::System.Int32 id, global::System.DateTime pubDate, global::System.String type, global::System.String user, global::System.String message, global::System.String image, global::System.String time, global::System.String large, global::System.String title, global::System.String description, global::System.String link, global::System.String storyImage, global::System.String storyText)
        {
            StoryEvent storyEvent = new StoryEvent();
            storyEvent.Id = id;
            storyEvent.PubDate = pubDate;
            storyEvent.Type = type;
            storyEvent.User = user;
            storyEvent.Message = message;
            storyEvent.Image = image;
            storyEvent.Time = time;
            storyEvent.Large = large;
            storyEvent.Title = title;
            storyEvent.Description = description;
            storyEvent.Link = link;
            storyEvent.StoryImage = storyImage;
            storyEvent.StoryText = storyText;
            return storyEvent;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Link
        {
            get
            {
                return _Link;
            }
            set
            {
                OnLinkChanging(value);
                ReportPropertyChanging("Link");
                _Link = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Link");
                OnLinkChanged();
            }
        }
        private global::System.String _Link;
        partial void OnLinkChanging(global::System.String value);
        partial void OnLinkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StoryImage
        {
            get
            {
                return _StoryImage;
            }
            set
            {
                OnStoryImageChanging(value);
                ReportPropertyChanging("StoryImage");
                _StoryImage = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StoryImage");
                OnStoryImageChanged();
            }
        }
        private global::System.String _StoryImage;
        partial void OnStoryImageChanging(global::System.String value);
        partial void OnStoryImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StoryText
        {
            get
            {
                return _StoryText;
            }
            set
            {
                OnStoryTextChanging(value);
                ReportPropertyChanging("StoryText");
                _StoryText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StoryText");
                OnStoryTextChanged();
            }
        }
        private global::System.String _StoryText;
        partial void OnStoryTextChanging(global::System.String value);
        partial void OnStoryTextChanged();

        #endregion
    
    }

    #endregion
    
}
